name: rpcad
channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python>=3.10
  - pip>=20.3
  - cudatoolkit=11.8
  - pytorch>=1.11.0
  - torchvision>=0.12.0
  - numpy>=1.19.2
  - pytorch-cuda=11.8
  - meshplot=0.4.0
  - ffmpeg=4.2.2
  - pip:
    - -r requirements.txt
    - -e .